spring:
  datasource:
    url: jdbc:postgresql://localhost:6001/
    username: postgres
    password: password


    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.PostgresSQLDialect

      sql:
        init:
          mode: always